# Deploy snapshots to Sonatype OSS repository

name: Deploy

concurrency: ${{ github.workflow }}

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Maven Deploy
        uses: wcm-io-devops/github-action-maven-deploy@v1
        with:
          java-version: 21
          sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
          sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}
